### ISSUE TITLE
import api failed, error msg "duplicate extension registered: descriptor.MethodOptions"

### ISSUE THREAD

**Issue by zackzhangkai** [istio/api#2097]
**Bug description**
when import api , there is a panic:

```bash
import _ "istio.io/api/networking/v1alpha3"

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterExtension(0x7b4d780)
       /vendor/github.com/gogo/protobuf/proto/extensions.go:595 +0x399
istio.io/gogo-genproto/googleapis/google/api.init.0()
     /vendor/istio.io/gogo-genproto/googleapis/google/api/annotations.pb.go:34 +0x2d
Exiting.
```

**Comment by zackzhangkai** [comment]
https://github.com/gogo/protobuf/issues/672

**Comment by zackzhangkai** [comment]
https://github.com/istio/istio/issues/35277
